FROM chialab/php:8.0-apache

# create non-root user
RUN useradd --create-home --shell /bin/bash --uid 1000 user

# init xdebug
RUN echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*

RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install \
    pcntl

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
        &&  docker-php-ext-enable redis

# Update composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# create cache directories for composer
RUN mkdir /.composer && chmod 777 -R /.composer
